name: Deploy to AWS

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      K8S_MANIFESTS_PATHS:
        required: true
        type: string
    secrets:
      REUSABLE_WORKFLOW_PAT:
        required: true
      DOCKER_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REUSABLE_WORKFLOW_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
          IFS=',' read -ra MANIFESTS <<< "${{ inputs.K8S_MANIFESTS_PATHS }}"
          for manifest in "${MANIFESTS[@]}"; do
            sed -i 's|${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g' $manifest
            sed -i 's|${IMAGE_TAG}|${{ inputs.IMAGE_TAG }}|g' $manifest
            kubectl apply -f $manifest
          done
