name: Deploy to AWS

on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
      K8S_MANIFESTS_PATHS:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ inputs.IMAGE_TAG }}
          aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}
          repository_name=${{ inputs.REPOSITORY_NAME }}
          docker build -t "$aws_account_id.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$repository_name:$IMAGE_TAG" .
          docker push "$aws_account_id.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$repository_name:$IMAGE_TAG"

      - name: Deploy to Kubernetes
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
          IFS=',' read -ra MANIFESTS <<< "${{ inputs.K8S_MANIFESTS_PATHS }}"
          for manifest in "${MANIFESTS[@]}"; do
            kubectl apply -f $manifest
          done
